#include "rms/control/ControlStatusModel.h"

namespace ta {
namespace rms {
namespace control {

namespace {
const char* kNotConnected = "NOT CONNECTED";
}

ControlStatusModel::ControlStatusModel(QObject* parent)
    : QAbstractListModel(parent)
{
}

void ControlStatusModel::setSources(RangeMonitor* monitor,
                                    RangeControlCoordinator* coordinator)
{
    m_monitor = monitor;
    m_coordinator = coordinator;
    refresh();
}

void ControlStatusModel::setTransportAttached(bool attached)
{
    if (m_transportAttached == attached)
        return;
    m_transportAttached = attached;
    refresh();
}

void ControlStatusModel::setKeyConfigured(bool configured, const QString& detail)
{
    m_keyConfigured = configured;
    m_keyDetail = detail;
    refresh();
}

void ControlStatusModel::refresh()
{
    beginResetModel();
    m_rows.clear();
    if (m_monitor) {
        for (int i = 0; i < m_monitor->nodeCount(); ++i) {
            const TargetNodeRecord* rec = m_monitor->nodeAt(i);
            if (!rec)
                continue;
            Row r;
            r.nodeId = rec->nodeId;
            r.laneLabel = rec->laneId.isEmpty() ? rec->nodeId : rec->laneId;
            r.unobserved = rec->unobservedShotCount();
            // WITHOUT A TRANSPORT, every lane reads NOT CONNECTED regardless of
            // what any in-process object believes. The channel state shown to an
            // operator must describe the range, not the software's optimism.
            if (m_transportAttached && m_keyConfigured && m_coordinator) {
                r.authenticated = m_coordinator->isAuthenticated(rec->nodeId);
                // The channel's OWN state, which is more than authenticated or
                // not: a lane the node restarted under passes through RESTART
                // DETECTED and REAUTHENTICATING on the way back, and an
                // operator watching a lane go quiet is owed those words rather
                // than a gap.
                r.channel = controlLinkStateName(m_coordinator->linkState(rec->nodeId));
                r.restarts = m_coordinator->restartsObserved(rec->nodeId);
                r.pendingCommands = m_coordinator->pendingCommandCount(rec->nodeId);
                r.syncQuality = syncQualityName(
                    m_coordinator->timeSync(rec->nodeId).quality);
                const ReconciliationWatermark w = m_coordinator->watermark(rec->nodeId);
                r.reconciledTo = w.nodeId.isEmpty() ? -1 : w.highestSequence;
            } else {
                r.channel = m_transportAttached && !m_keyConfigured
                                ? QStringLiteral("NOT CONFIGURED")
                                : QLatin1String(kNotConnected);
                r.syncQuality = syncQualityName(SyncQuality::Unusable);
            }
            m_rows.append(r);
        }
    }
    endResetModel();
    emit summaryChanged();
}

int ControlStatusModel::authenticatedCount() const
{
    int n = 0;
    for (const Row& r : m_rows) if (r.authenticated) ++n;
    return n;
}

int ControlStatusModel::unobservedShots() const
{
    int n = 0;
    for (const Row& r : m_rows) n += r.unobserved;
    return n;
}

int ControlStatusModel::lanesBehind() const
{
    int n = 0;
    for (const Row& r : m_rows) if (r.unobserved > 0) ++n;
    return n;
}

QString ControlStatusModel::statusLine() const
{
    if (!m_transportAttached) {
        // The whole point of the banner. No hedging, no "standby", no spinner
        // that suggests it is about to connect.
        return QStringLiteral(
            "CONTROL CHANNEL NOT ENABLED - this build observes only. "
            "Lane commands are not available.");
    }
    if (!m_keyConfigured) {
        // A DIFFERENT problem from the one above, and the operator can fix this
        // one: the range key is generated by the node and copied across. Saying
        // "not enabled" here would send them looking for a build problem that
        // does not exist.
        QString s = QStringLiteral(
            "CONTROL NOT CONFIGURED - no range key on this laptop, so lanes "
            "cannot be authenticated and shots cannot be recovered. "
            "Telemetry is unaffected.");
        if (!m_keyDetail.isEmpty())
            s += QStringLiteral(" (%1)").arg(m_keyDetail);
        return s;
    }
    if (m_rows.isEmpty())
        return QStringLiteral("Control channel enabled. No lanes are reporting yet.");

    const int auth = authenticatedCount();
    QString s = QStringLiteral("Control channel enabled. %1 of %2 lanes authenticated")
                    .arg(auth).arg(m_rows.size());
    // A lane the node restarted under is NAMED as such while it recovers. An
    // operator who saw a station reboot should read that back, not a silent
    // dip in the authenticated count.
    const int recovering = lanesRecovering();
    if (recovering > 0)
        s += QStringLiteral("; %1 lane%2 recovering from a node restart")
                 .arg(recovering).arg(recovering == 1 ? "" : "s");
    const int behind = lanesBehind();
    if (behind > 0)
        s += QStringLiteral("; %1 lane%2 behind by %3 shot%4 - recovering")
                 .arg(behind).arg(behind == 1 ? "" : "s")
                 .arg(unobservedShots()).arg(unobservedShots() == 1 ? "" : "s");
    return s + QLatin1Char('.');
}

int ControlStatusModel::lanesRecovering() const
{
    int n = 0;
    for (const Row& r : m_rows) {
        if (r.channel == QLatin1String("RESTART DETECTED")
            || r.channel == QLatin1String("REAUTHENTICATING")
            || r.channel == QLatin1String("REPLAYING"))
            ++n;
    }
    return n;
}

QString ControlStatusModel::tone() const
{
    // Not connected is NEUTRAL, not a warning: a build without a control
    // transport is behaving correctly, and colouring it red would train
    // operators to ignore the colour that means something is wrong.
    if (!m_transportAttached)
        return QStringLiteral("neutral");
    // Not configured IS a warning: unlike a build with no transport, this one
    // could be recovering shots and is not.
    if (!m_keyConfigured)
        return QStringLiteral("warn");
    if (m_rows.isEmpty())
        return QStringLiteral("neutral");
    if (authenticatedCount() < m_rows.size())
        return QStringLiteral("warn");
    return lanesBehind() > 0 ? QStringLiteral("warn") : QStringLiteral("live");
}

int ControlStatusModel::rowCount(const QModelIndex& parent) const
{
    return parent.isValid() ? 0 : m_rows.size();
}

QVariant ControlStatusModel::data(const QModelIndex& index, int role) const
{
    if (!index.isValid() || index.row() < 0 || index.row() >= m_rows.size())
        return QVariant();
    const Row& r = m_rows.at(index.row());
    switch (role) {
    case NodeIdRole:       return r.nodeId;
    case LaneLabelRole:    return r.laneLabel;
    case ChannelRole:      return r.channel;
    case SyncQualityRole:  return r.syncQuality;
    case UnobservedRole:   return r.unobserved;
    case ReconciledToRole: return r.reconciledTo;
    case RestartsRole:     return r.restarts;
    case PendingRole:      return r.pendingCommands;
    case ToneRole:
        if (!r.authenticated) return QStringLiteral("neutral");
        return r.unobserved > 0 ? QStringLiteral("warn") : QStringLiteral("live");
    default: break;
    }
    return QVariant();
}

QHash<int, QByteArray> ControlStatusModel::roleNames() const
{
    return {{NodeIdRole, "nodeId"},
            {LaneLabelRole, "laneLabel"},
            {ChannelRole, "channel"},
            {SyncQualityRole, "syncQuality"},
            {UnobservedRole, "unobserved"},
            {ReconciledToRole, "reconciledTo"},
            {RestartsRole, "restarts"},
            {PendingRole, "pendingCommands"},
            {ToneRole, "tone"}};
}

} // namespace control
} // namespace rms
} // namespace ta
